package openapi

import (
	"errors"
	"net/http"

	"github.com/Authula/authula/openapi"
	"github.com/Authula/authula/plugins/organizations/types"
)

func RegisterOpenAPIDocs(svc openapi.OpenAPIService) error {
	return errors.Join(
		// Organizations
		svc.AddOperation(
			http.MethodPost,
			"/organizations",
			openapi.WithOperationID("createOrganization"),
			openapi.WithSummary("Create organization"),
			openapi.WithDescription("Creates a new organization with the authenticated user as the owner."),
			openapi.WithTags("Organizations"),
			openapi.WithRequest(&types.CreateOrganizationRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.Organization{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations",
			openapi.WithOperationID("listOrganizations"),
			openapi.WithSummary("List organizations"),
			openapi.WithDescription("Lists all organizations owned by the authenticated user."),
			openapi.WithTags("Organizations"),
			openapi.WithResponseStatus(http.StatusOK, &[]types.Organization{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}",
			openapi.WithOperationID("getOrganization"),
			openapi.WithSummary("Get organization"),
			openapi.WithDescription("Retrieves an organization by its ID."),
			openapi.WithTags("Organizations"),
			openapi.WithRequest(&types.OrganizationID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.Organization{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			"/organizations/{organization_id}",
			openapi.WithOperationID("updateOrganization"),
			openapi.WithSummary("Update organization"),
			openapi.WithDescription("Updates an existing organization."),
			openapi.WithTags("Organizations"),
			openapi.WithRequest(&types.OrganizationID{}),
			openapi.WithRequest(&types.UpdateOrganizationRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.Organization{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			"/organizations/{organization_id}",
			openapi.WithOperationID("deleteOrganization"),
			openapi.WithSummary("Delete organization"),
			openapi.WithDescription("Deletes an organization."),
			openapi.WithTags("Organizations"),
			openapi.WithRequest(&types.OrganizationID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteOrganizationResponse{}),
		),

		// Invitations
		svc.AddOperation(
			http.MethodPost,
			"/organizations/{organization_id}/invitations",
			openapi.WithOperationID("createOrganizationInvitation"),
			openapi.WithSummary("Create invitation"),
			openapi.WithDescription("Creates an invitation for a user to join an organization."),
			openapi.WithTags("Organization Invitations"),
			openapi.WithRequest(&types.OrganizationID{}),
			openapi.WithRequest(&types.CreateOrganizationInvitationQuery{}),
			openapi.WithRequest(&types.CreateOrganizationInvitationRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.OrganizationInvitation{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/invitations",
			openapi.WithOperationID("listOrganizationInvitations"),
			openapi.WithSummary("List invitations"),
			openapi.WithDescription("Lists all invitations for an organization."),
			openapi.WithTags("Organization Invitations"),
			openapi.WithRequest(&types.OrganizationID{}),
			openapi.WithResponseStatus(http.StatusOK, &[]types.GetOrganizationInvitationResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/invitations/{invitation_id}",
			openapi.WithOperationID("getOrganizationInvitation"),
			openapi.WithSummary("Get invitation"),
			openapi.WithDescription("Retrieves a single invitation."),
			openapi.WithTags("Organization Invitations"),
			openapi.WithRequest(&types.InvitationID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.GetOrganizationInvitationResponse{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			"/organizations/{organization_id}/invitations/{invitation_id}/revoke",
			openapi.WithOperationID("revokeOrganizationInvitation"),
			openapi.WithSummary("Revoke invitation"),
			openapi.WithDescription("Revokes a pending invitation."),
			openapi.WithTags("Organization Invitations"),
			openapi.WithRequest(&types.InvitationID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationInvitation{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			"/organizations/{organization_id}/invitations/{invitation_id}/accept",
			openapi.WithOperationID("acceptOrganizationInvitation"),
			openapi.WithSummary("Accept invitation"),
			openapi.WithDescription("Accepts an invitation to join an organization."),
			openapi.WithTags("Organization Invitations"),
			openapi.WithRequest(&types.AcceptOrganizationInvitationQuery{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationInvitation{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			"/organizations/{organization_id}/invitations/{invitation_id}/reject",
			openapi.WithOperationID("rejectOrganizationInvitation"),
			openapi.WithSummary("Reject invitation"),
			openapi.WithDescription("Rejects an invitation to join an organization."),
			openapi.WithTags("Organization Invitations"),
			openapi.WithRequest(&types.InvitationID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationInvitation{}),
		),

		// Members
		svc.AddOperation(
			http.MethodPost,
			"/organizations/{organization_id}/members",
			openapi.WithOperationID("addOrganizationMember"),
			openapi.WithSummary("Add member"),
			openapi.WithDescription("Adds a user as a member of an organization with the specified role."),
			openapi.WithTags("Organization Members"),
			openapi.WithRequest(&types.OrganizationID{}),
			openapi.WithRequest(&types.AddOrganizationMemberRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.OrganizationMember{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/members",
			openapi.WithOperationID("listOrganizationMembers"),
			openapi.WithSummary("List members"),
			openapi.WithDescription("Lists all members of an organization with pagination."),
			openapi.WithTags("Organization Members"),
			openapi.WithRequest(&types.ListOrganizationMembersRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &[]types.OrganizationMemberResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/members/{member_id}",
			openapi.WithOperationID("getOrganizationMember"),
			openapi.WithSummary("Get member"),
			openapi.WithDescription("Retrieves a single organization member by ID with nested user data."),
			openapi.WithTags("Organization Members"),
			openapi.WithRequest(&types.MemberID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationMemberResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/members/by-user/{user_id}",
			openapi.WithOperationID("getOrganizationMemberByUserID"),
			openapi.WithSummary("Get member by user ID"),
			openapi.WithDescription("Retrieves an organization member by the user's ID with nested user data."),
			openapi.WithTags("Organization Members"),
			openapi.WithRequest(&types.MemberUserID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationMemberResponse{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			"/organizations/{organization_id}/members/{member_id}",
			openapi.WithOperationID("updateOrganizationMember"),
			openapi.WithSummary("Update member"),
			openapi.WithDescription("Updates the role of an organization member."),
			openapi.WithTags("Organization Members"),
			openapi.WithRequest(&types.MemberID{}),
			openapi.WithRequest(&types.UpdateOrganizationMemberRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationMember{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			"/organizations/{organization_id}/members/{member_id}",
			openapi.WithOperationID("deleteOrganizationMember"),
			openapi.WithSummary("Delete member"),
			openapi.WithDescription("Removes a member from an organization."),
			openapi.WithTags("Organization Members"),
			openapi.WithRequest(&types.MemberID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteOrganizationMemberResponse{}),
		),

		// Teams
		svc.AddOperation(
			http.MethodPost,
			"/organizations/{organization_id}/teams",
			openapi.WithOperationID("createOrganizationTeam"),
			openapi.WithSummary("Create team"),
			openapi.WithDescription("Creates a new team within an organization."),
			openapi.WithTags("Organization Teams"),
			openapi.WithRequest(&types.OrganizationID{}),
			openapi.WithRequest(&types.CreateOrganizationTeamRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.OrganizationTeam{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/teams",
			openapi.WithOperationID("listOrganizationTeams"),
			openapi.WithSummary("List teams"),
			openapi.WithDescription("Lists all teams within an organization."),
			openapi.WithTags("Organization Teams"),
			openapi.WithRequest(&types.OrganizationID{}),
			openapi.WithResponseStatus(http.StatusOK, &[]types.OrganizationTeam{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/teams/{team_id}",
			openapi.WithOperationID("getOrganizationTeam"),
			openapi.WithSummary("Get team"),
			openapi.WithDescription("Retrieves a single team by its ID."),
			openapi.WithTags("Organization Teams"),
			openapi.WithRequest(&types.TeamID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationTeam{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			"/organizations/{organization_id}/teams/{team_id}",
			openapi.WithOperationID("updateOrganizationTeam"),
			openapi.WithSummary("Update team"),
			openapi.WithDescription("Updates an existing team."),
			openapi.WithTags("Organization Teams"),
			openapi.WithRequest(&types.TeamID{}),
			openapi.WithRequest(&types.UpdateOrganizationTeamRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationTeam{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			"/organizations/{organization_id}/teams/{team_id}",
			openapi.WithOperationID("deleteOrganizationTeam"),
			openapi.WithSummary("Delete team"),
			openapi.WithDescription("Deletes a team."),
			openapi.WithTags("Organization Teams"),
			openapi.WithRequest(&types.TeamID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteOrganizationTeamResponse{}),
		),

		// Team Members
		svc.AddOperation(
			http.MethodPost,
			"/organizations/{organization_id}/teams/{team_id}/members",
			openapi.WithOperationID("addOrganizationTeamMember"),
			openapi.WithSummary("Add team member"),
			openapi.WithDescription("Adds a member to a team."),
			openapi.WithTags("Organization Team Members"),
			openapi.WithRequest(&types.TeamID{}),
			openapi.WithRequest(&types.AddOrganizationTeamMemberRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.OrganizationTeamMember{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/teams/{team_id}/members",
			openapi.WithOperationID("listOrganizationTeamMembers"),
			openapi.WithSummary("List team members"),
			openapi.WithDescription("Lists all members of a team with pagination."),
			openapi.WithTags("Organization Team Members"),
			openapi.WithRequest(&types.ListOrganizationTeamMembersRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &[]types.OrganizationTeamMemberResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			"/organizations/{organization_id}/teams/{team_id}/members/{member_id}",
			openapi.WithOperationID("getOrganizationTeamMember"),
			openapi.WithSummary("Get team member"),
			openapi.WithDescription("Retrieves a single team member by ID with nested member and user data."),
			openapi.WithTags("Organization Team Members"),
			openapi.WithRequest(&types.TeamMemberID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.OrganizationTeamMemberResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			"/organizations/{organization_id}/teams/{team_id}/members/{member_id}",
			openapi.WithOperationID("deleteOrganizationTeamMember"),
			openapi.WithSummary("Delete team member"),
			openapi.WithDescription("Removes a member from a team."),
			openapi.WithTags("Organization Team Members"),
			openapi.WithRequest(&types.TeamMemberID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteOrganizationTeamMemberResponse{}),
		),
	)
}
