package openapi

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/Authula/authula/openapi"
	"github.com/Authula/authula/plugins/admin/types"
)

func RegisterOpenAPIDocs(svc openapi.OpenAPIService, basePath string) error {
	return errors.Join(
		// Users
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/users", basePath),
			openapi.WithOperationID("createUser"),
			openapi.WithSummary("Create user"),
			openapi.WithDescription("Creates a new user with the specified attributes."),
			openapi.WithTags("Admin Users"),
			openapi.WithRequest(&types.CreateUserRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.CreateUserResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/users", basePath),
			openapi.WithOperationID("listUsers"),
			openapi.WithSummary("List users"),
			openapi.WithDescription("Lists users with cursor-based pagination."),
			openapi.WithTags("Admin Users"),
			openapi.WithRequest(&types.ListUsersQuery{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UsersPage{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/users/{user_id}", basePath),
			openapi.WithOperationID("getUser"),
			openapi.WithSummary("Get user by ID"),
			openapi.WithDescription("Retrieves a user by their ID."),
			openapi.WithTags("Admin Users"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.GetUserByIDResponse{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			fmt.Sprintf("%s/admin/users/{user_id}", basePath),
			openapi.WithOperationID("updateUser"),
			openapi.WithSummary("Update user"),
			openapi.WithDescription("Updates a user's attributes."),
			openapi.WithTags("Admin Users"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithRequest(&types.UpdateUserRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UpdateUserResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			fmt.Sprintf("%s/admin/users/{user_id}", basePath),
			openapi.WithOperationID("deleteUser"),
			openapi.WithSummary("Delete user"),
			openapi.WithDescription("Deletes a user."),
			openapi.WithTags("Admin Users"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteUserResponse{}),
		),

		// Accounts
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/users/{user_id}/accounts", basePath),
			openapi.WithOperationID("createAccount"),
			openapi.WithSummary("Create account"),
			openapi.WithDescription("Creates a new account for a user."),
			openapi.WithTags("Admin Accounts"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithRequest(&types.CreateAccountRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.CreateAccountResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/users/{user_id}/accounts", basePath),
			openapi.WithOperationID("listUserAccounts"),
			openapi.WithSummary("List user accounts"),
			openapi.WithDescription("Lists all accounts for a user."),
			openapi.WithTags("Admin Accounts"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UserAccountsResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/accounts/{id}", basePath),
			openapi.WithOperationID("getAccount"),
			openapi.WithSummary("Get account by ID"),
			openapi.WithDescription("Retrieves an account by its ID."),
			openapi.WithTags("Admin Accounts"),
			openapi.WithRequest(&types.AdminAccountID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.GetAccountByIDResponse{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			fmt.Sprintf("%s/admin/accounts/{id}", basePath),
			openapi.WithOperationID("updateAccount"),
			openapi.WithSummary("Update account"),
			openapi.WithDescription("Updates an account's attributes."),
			openapi.WithTags("Admin Accounts"),
			openapi.WithRequest(&types.AdminAccountID{}),
			openapi.WithRequest(&types.UpdateAccountRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UpdateAccountResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			fmt.Sprintf("%s/admin/accounts/{id}", basePath),
			openapi.WithOperationID("deleteAccount"),
			openapi.WithSummary("Delete account"),
			openapi.WithDescription("Deletes an account."),
			openapi.WithTags("Admin Accounts"),
			openapi.WithRequest(&types.AdminAccountID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteAccountResponse{}),
		),

		// User state
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/users/{user_id}/state", basePath),
			openapi.WithOperationID("getUserState"),
			openapi.WithSummary("Get user state"),
			openapi.WithDescription("Retrieves the state of a user."),
			openapi.WithTags("Admin User State"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.GetUserStateResponse{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/users/{user_id}/state", basePath),
			openapi.WithOperationID("createUserState"),
			openapi.WithSummary("Create user state"),
			openapi.WithDescription("Creates the state for a user."),
			openapi.WithTags("Admin User State"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithRequest(&types.CreateUserStateRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.UpsertUserStateResponse{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			fmt.Sprintf("%s/admin/users/{user_id}/state", basePath),
			openapi.WithOperationID("updateUserState"),
			openapi.WithSummary("Update user state"),
			openapi.WithDescription("Updates the state of a user."),
			openapi.WithTags("Admin User State"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithRequest(&types.UpsertUserStateRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UpsertUserStateResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			fmt.Sprintf("%s/admin/users/{user_id}/state", basePath),
			openapi.WithOperationID("deleteUserState"),
			openapi.WithSummary("Delete user state"),
			openapi.WithDescription("Deletes the state of a user."),
			openapi.WithTags("Admin User State"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteUserStateResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/users/states/banned", basePath),
			openapi.WithOperationID("listBannedUserStates"),
			openapi.WithSummary("List banned user states"),
			openapi.WithDescription("Lists all banned user states."),
			openapi.WithTags("Admin User State"),
			openapi.WithResponseStatus(http.StatusOK, &[]types.AdminUserState{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/users/{user_id}/ban", basePath),
			openapi.WithOperationID("banUser"),
			openapi.WithSummary("Ban user"),
			openapi.WithDescription("Bans a user."),
			openapi.WithTags("Admin User State"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithRequest(&types.BanUserRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.BanUserResponse{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/users/{user_id}/unban", basePath),
			openapi.WithOperationID("unbanUser"),
			openapi.WithSummary("Unban user"),
			openapi.WithDescription("Unbans a user."),
			openapi.WithTags("Admin User State"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UnbanUserResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/users/{user_id}/sessions", basePath),
			openapi.WithOperationID("listUserSessions"),
			openapi.WithSummary("List user sessions"),
			openapi.WithDescription("Lists all sessions for a user."),
			openapi.WithTags("Admin User State"),
			openapi.WithRequest(&types.AdminUserID{}),
			openapi.WithResponseStatus(http.StatusOK, &[]types.AdminUserSession{}),
		),

		// Session state
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/sessions/{session_id}/state", basePath),
			openapi.WithOperationID("getSessionState"),
			openapi.WithSummary("Get session state"),
			openapi.WithDescription("Retrieves the state of a session."),
			openapi.WithTags("Admin Session State"),
			openapi.WithRequest(&types.AdminSessionID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.GetSessionStateResponse{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/sessions/{session_id}/state", basePath),
			openapi.WithOperationID("createSessionState"),
			openapi.WithSummary("Create session state"),
			openapi.WithDescription("Creates the state for a session."),
			openapi.WithTags("Admin Session State"),
			openapi.WithRequest(&types.AdminSessionID{}),
			openapi.WithRequest(&types.CreateSessionStateRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.UpsertSessionStateResponse{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			fmt.Sprintf("%s/admin/sessions/{session_id}/state", basePath),
			openapi.WithOperationID("updateSessionState"),
			openapi.WithSummary("Update session state"),
			openapi.WithDescription("Updates the state of a session."),
			openapi.WithTags("Admin Session State"),
			openapi.WithRequest(&types.AdminSessionID{}),
			openapi.WithRequest(&types.UpsertSessionStateRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UpsertSessionStateResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			fmt.Sprintf("%s/admin/sessions/{session_id}/state", basePath),
			openapi.WithOperationID("deleteSessionState"),
			openapi.WithSummary("Delete session state"),
			openapi.WithDescription("Deletes the state of a session."),
			openapi.WithTags("Admin Session State"),
			openapi.WithRequest(&types.AdminSessionID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteSessionStateResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/sessions/states/revoked", basePath),
			openapi.WithOperationID("listRevokedSessionStates"),
			openapi.WithSummary("List revoked session states"),
			openapi.WithDescription("Lists all revoked session states."),
			openapi.WithTags("Admin Session State"),
			openapi.WithResponseStatus(http.StatusOK, &[]types.AdminSessionState{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/sessions/{session_id}/revoke", basePath),
			openapi.WithOperationID("revokeSession"),
			openapi.WithSummary("Revoke session"),
			openapi.WithDescription("Revokes a session."),
			openapi.WithTags("Admin Session State"),
			openapi.WithRequest(&types.AdminSessionID{}),
			openapi.WithRequest(&types.RevokeSessionRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.RevokeSessionResponse{}),
		),

		// Impersonation
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/impersonations", basePath),
			openapi.WithOperationID("listImpersonations"),
			openapi.WithSummary("List impersonations"),
			openapi.WithDescription("Lists all impersonations."),
			openapi.WithTags("Admin Impersonation"),
			openapi.WithResponseStatus(http.StatusOK, &[]types.Impersonation{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/admin/impersonations/{impersonation_id}", basePath),
			openapi.WithOperationID("getImpersonation"),
			openapi.WithSummary("Get impersonation by ID"),
			openapi.WithDescription("Retrieves an impersonation by its ID."),
			openapi.WithTags("Admin Impersonation"),
			openapi.WithRequest(&types.AdminImpersonationID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.GetImpersonationByIDResponse{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/impersonations", basePath),
			openapi.WithOperationID("startImpersonation"),
			openapi.WithSummary("Start impersonation"),
			openapi.WithDescription("Starts an impersonation session as a target user."),
			openapi.WithTags("Admin Impersonation"),
			openapi.WithRequest(&types.StartImpersonationRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.StartImpersonationResponse{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/admin/impersonations/{impersonation_id}/stop", basePath),
			openapi.WithOperationID("stopImpersonation"),
			openapi.WithSummary("Stop impersonation"),
			openapi.WithDescription("Stops an impersonation session and restores the original session."),
			openapi.WithTags("Admin Impersonation"),
			openapi.WithRequest(&types.AdminImpersonationID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.StopImpersonationResponse{}),
		),
	)
}
