package openapi

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/Authula/authula/openapi"
	"github.com/Authula/authula/plugins/access-control/types"
)

func RegisterOpenAPIDocs(svc openapi.OpenAPIService, basePath string) error {
	return errors.Join(
		// Roles
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/access-control/roles", basePath),
			openapi.WithOperationID("createRole"),
			openapi.WithSummary("Create role"),
			openapi.WithDescription("Creates a new role."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.CreateRoleRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.CreateRoleResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/access-control/roles", basePath),
			openapi.WithOperationID("listRoles"),
			openapi.WithSummary("List roles"),
			openapi.WithDescription("Lists all roles."),
			openapi.WithTags("Access Control"),
			openapi.WithResponseStatus(http.StatusOK, &[]types.Role{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/access-control/roles/by-name/{role_name}", basePath),
			openapi.WithOperationID("getRoleByName"),
			openapi.WithSummary("Get role by name"),
			openapi.WithDescription("Retrieves a role by its name."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.RoleName{}),
			openapi.WithResponseStatus(http.StatusOK, &types.Role{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/access-control/roles/{role_id}", basePath),
			openapi.WithOperationID("getRole"),
			openapi.WithSummary("Get role by ID"),
			openapi.WithDescription("Retrieves a role by its ID, including its permissions."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.RoleID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.RoleDetails{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			fmt.Sprintf("%s/access-control/roles/{role_id}", basePath),
			openapi.WithOperationID("updateRole"),
			openapi.WithSummary("Update role"),
			openapi.WithDescription("Updates a role's attributes."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.RoleID{}),
			openapi.WithRequest(&types.UpdateRoleRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UpdateRoleResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			fmt.Sprintf("%s/access-control/roles/{role_id}", basePath),
			openapi.WithOperationID("deleteRole"),
			openapi.WithSummary("Delete role"),
			openapi.WithDescription("Deletes a role."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.RoleID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeleteRoleResponse{}),
		),

		// Permissions
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/access-control/permissions", basePath),
			openapi.WithOperationID("createPermission"),
			openapi.WithSummary("Create permission"),
			openapi.WithDescription("Creates a new permission."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.CreatePermissionRequest{}),
			openapi.WithResponseStatus(http.StatusCreated, &types.CreatePermissionResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/access-control/permissions", basePath),
			openapi.WithOperationID("listPermissions"),
			openapi.WithSummary("List permissions"),
			openapi.WithDescription("Lists all permissions."),
			openapi.WithTags("Access Control"),
			openapi.WithResponseStatus(http.StatusOK, &[]types.Permission{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/access-control/permissions/{permission_id}", basePath),
			openapi.WithOperationID("getPermission"),
			openapi.WithSummary("Get permission by ID"),
			openapi.WithDescription("Retrieves a permission by its ID."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.PermissionID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.Permission{}),
		),
		svc.AddOperation(
			http.MethodPatch,
			fmt.Sprintf("%s/access-control/permissions/{permission_id}", basePath),
			openapi.WithOperationID("updatePermission"),
			openapi.WithSummary("Update permission"),
			openapi.WithDescription("Updates a permission's description."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.PermissionID{}),
			openapi.WithRequest(&types.UpdatePermissionRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.UpdatePermissionResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			fmt.Sprintf("%s/access-control/permissions/{permission_id}", basePath),
			openapi.WithOperationID("deletePermission"),
			openapi.WithSummary("Delete permission"),
			openapi.WithDescription("Deletes a permission."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.PermissionID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.DeletePermissionResponse{}),
		),

		// Role permissions
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/access-control/roles/{role_id}/permissions", basePath),
			openapi.WithOperationID("addRolePermission"),
			openapi.WithSummary("Assign permission to role"),
			openapi.WithDescription("Assigns a permission to a role."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.RoleID{}),
			openapi.WithRequest(&types.AddRolePermissionRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.AddRolePermissionResponse{}),
		),
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/access-control/roles/{role_id}/permissions", basePath),
			openapi.WithOperationID("listRolePermissions"),
			openapi.WithSummary("List role permissions"),
			openapi.WithDescription("Lists all permissions assigned to a role."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.RoleID{}),
			openapi.WithResponseStatus(http.StatusOK, &[]types.UserPermissionInfo{}),
		),
		svc.AddOperation(
			http.MethodPut,
			fmt.Sprintf("%s/access-control/roles/{role_id}/permissions", basePath),
			openapi.WithOperationID("replaceRolePermissions"),
			openapi.WithSummary("Replace role permissions"),
			openapi.WithDescription("Replaces all permissions assigned to a role with a new set."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.RoleID{}),
			openapi.WithRequest(&types.ReplaceRolePermissionsRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.ReplaceRolePermissionResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			fmt.Sprintf("%s/access-control/roles/{role_id}/permissions/{permission_id}", basePath),
			openapi.WithOperationID("removeRolePermission"),
			openapi.WithSummary("Remove role permission"),
			openapi.WithDescription("Removes a permission from a role."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.RolePermissionID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.RemoveRolePermissionResponse{}),
		),

		// User roles
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/access-control/users/{user_id}/roles", basePath),
			openapi.WithOperationID("listUserRoles"),
			openapi.WithSummary("List user roles"),
			openapi.WithDescription("Lists all roles assigned to a user."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.UserID{}),
			openapi.WithResponseStatus(http.StatusOK, &[]types.UserRoleInfo{}),
		),
		svc.AddOperation(
			http.MethodPut,
			fmt.Sprintf("%s/access-control/users/{user_id}/roles", basePath),
			openapi.WithOperationID("replaceUserRoles"),
			openapi.WithSummary("Replace user roles"),
			openapi.WithDescription("Replaces all roles assigned to a user with a new set."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.UserID{}),
			openapi.WithRequest(&types.ReplaceUserRolesRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.ReplaceUserRolesResponse{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/access-control/users/{user_id}/roles", basePath),
			openapi.WithOperationID("assignUserRole"),
			openapi.WithSummary("Assign role to user"),
			openapi.WithDescription("Assigns a role to a user."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.UserID{}),
			openapi.WithRequest(&types.AssignUserRoleRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.AssignUserRoleResponse{}),
		),
		svc.AddOperation(
			http.MethodDelete,
			fmt.Sprintf("%s/access-control/users/{user_id}/roles/{role_id}", basePath),
			openapi.WithOperationID("removeUserRole"),
			openapi.WithSummary("Remove user role"),
			openapi.WithDescription("Removes a role from a user."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.UserRoleID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.RemoveUserRoleResponse{}),
		),

		// User permissions
		svc.AddOperation(
			http.MethodGet,
			fmt.Sprintf("%s/access-control/users/{user_id}/permissions", basePath),
			openapi.WithOperationID("getUserPermissions"),
			openapi.WithSummary("Get user permissions"),
			openapi.WithDescription("Retrieves all permissions granted to a user through their roles."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.UserID{}),
			openapi.WithResponseStatus(http.StatusOK, &types.GetUserPermissionsResponse{}),
		),
		svc.AddOperation(
			http.MethodPost,
			fmt.Sprintf("%s/access-control/users/{user_id}/permissions/check", basePath),
			openapi.WithOperationID("checkUserPermissions"),
			openapi.WithSummary("Check user permissions"),
			openapi.WithDescription("Checks whether a user has all the specified permissions."),
			openapi.WithTags("Access Control"),
			openapi.WithRequest(&types.UserID{}),
			openapi.WithRequest(&types.CheckUserPermissionsRequest{}),
			openapi.WithResponseStatus(http.StatusOK, &types.CheckUserPermissionsResponse{}),
		),
	)
}
