package constants

const (
	UsersCreatePermission             = "admin:users:create"
	UsersListPermission               = "admin:users:list"
	UsersReadPermission               = "admin:users:read"
	UsersUpdatePermission             = "admin:users:update"
	UsersDeletePermission             = "admin:users:delete"
	AccountsCreatePermission          = "admin:accounts:create"
	AccountsListPermission            = "admin:accounts:list"
	AccountsReadPermission            = "admin:accounts:read"
	AccountsUpdatePermission          = "admin:accounts:update"
	AccountsDeletePermission          = "admin:accounts:delete"
	UserStateReadPermission           = "admin:user-state:read"
	UserStateCreatePermission         = "admin:user-state:create"
	UserStateUpdatePermission         = "admin:user-state:update"
	UserStateDeletePermission         = "admin:user-state:delete"
	UserStateBanPermission            = "admin:user-state:ban"
	UserStateUnbanPermission          = "admin:user-state:unban"
	UserStateListBannedPermission     = "admin:user-state:list-banned"
	UserStateListSessionsPermission   = "admin:user-state:list-sessions"
	SessionStateReadPermission        = "admin:session-state:read"
	SessionStateCreatePermission      = "admin:session-state:create"
	SessionStateUpdatePermission      = "admin:session-state:update"
	SessionStateDeletePermission      = "admin:session-state:delete"
	SessionStateRevokePermission      = "admin:session-state:revoke"
	SessionStateListRevokedPermission = "admin:session-state:list-revoked"
	ImpersonationsListPermission      = "admin:impersonations:list"
	ImpersonationsReadPermission      = "admin:impersonations:read"
	ImpersonationsStartPermission     = "admin:impersonations:start"
	ImpersonationsStopPermission      = "admin:impersonations:stop"
)
